import { getProducts } from "@/actions/server/product";
import ProductCard from "@/components/cards/ProductCard";
// import products from "@/components/home/Products";
import React from "react";


export const metadata = {
  title: "All Products", 
  description: "Generated by create next app",
};

const ProductsPage = async () => {
  const products = await fetch("http://localhost:5000/products", {
        method: "GET",
        headers: {
            "Content-Type": "application/json",
        },
    }).then((res) => res.json());

  // const products = await getProducts();
  // console.log(products)
  return (
    <div>
            <h1 className="text-2xl font-bold mb-4">Our Products</h1>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                {products.map((product) => (
                    <ProductCard key={product._id} product={product} />
                ))}
            </div>
        </div>
  );
};

export default ProductsPage;
