"use server";
import React from 'react';
// import products from "@/data/products.json";
import ProductCard from '../cards/ProductCard';
import { getProducts } from '@/actions/server/product';

export const metadata = {
  title: "AllProducts",
  description: "Generated by create next app",
}; 

const Products = async() => {
    const allProducts = await getProducts();
    return (
        <div>
            <h1 className="text-2xl font-bold mb-4">Our Products</h1>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                {allProducts.map((product) => (
                    <ProductCard key={product._id} product={product} />
                ))}
            </div>
        </div>
    );
};

export default Products;